---
random_seed: 0
environment:
  # Example map will be loaded if map_config_location is empty while random_generation is false
  random_generation: false
  map_config_location: map/example_map/config_example_map.yaml
  render: false  # More samples will be taken for evaluation if render is false, which allows calculation of means and stdev (render should be False for proper evaluation)
  render_mode: human_fast # human or human_fast
# Agent and expert policies
policy_type:
  agent: 
    downsample_method: simple  # it selects a bunch of scan data points
    observation_shape: 1080  # maximum number of scan points
    # TODO: downsample option for CNN and ViT
    model: mlp
    hidden_dim: 256
    learning_rate: 0.001
  # TODO: YAML config for Transformer 
  expert:
    behavior: waypoint_follower

